### ISSUE TITLE
Add CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by RaoOfPhysics** [alan-turing-institute/asg-community#4]

**Comment by malvikasharan** [comment]
Since the project is mainly involving the Turing members, I have linked the relevant documents in the Contributing guideline: 
- [Equality, Diversity and Inclusion framework](https://www.turing.ac.uk/about-us/equality-diversity-and-inclusion/EDI-framework)
- [Events code of conduct](https://www.turing.ac.uk/events/policies-and-guidelines)

Closing this issue as we won't be creating a separate Code of Conduct. Added these resources on the README page as well.
